### ISSUE TITLE
'yarn deployment-build' isn't exiting early

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#155]
Right now our stumptown-content git submodule pointer is a bit messed up. There's stuff built in `stumptown/packaged/` that's causing errors to be thrown but it still carries on. 

Steps to reproduce:

```
▶ yarn deployment-build
...
{
  type: 'link_list',
  value: { title: 'Learn HTML', content: [ [Object], [Object] ] }
}
Rendering HTML failed!
      uri=/en-US/docs/Web/HTML
      filePath=/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/stumptown/packaged/html/HTML.json
(node:4734) UnhandledPromiseRejectionWarning: Error: No idea how to handle a 'link_list' section
    at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:191:13
    at Array.map (<anonymous>)
    at map (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:148:19)
    at processChild (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3090:1)
    at resolve (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:1)
    at ReactDOMServerRenderer.render (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:1)
    at ReactDOMServerRenderer.read (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:1)
    at renderToString (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:1)
    at ./render.js.__webpack_exports__.default (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/render.js:31:34)
    at buildHtmlAndJson (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/index.js:118:24)
(node:4734) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4734) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{
  type: 'example',
  value: {
    description: {
      title: 'Specifying colors in stylesheets',
...
✨  Done in 19.57s.

▶ echo $?
0
```

In `stumptown/packaged/html/HTML.json` there's a key on the `document.body` that is currently unsupported. I.e. we don't have a React component to deal with it. That's a real problem but the pressing problem is that that error isn't dealt with properly. 

If the renderer's `cli` can't deal with the `stumptown-content` it should fail hard break things. It basically means that the `stumptown-renderer` and `stumptown-content` disagree and need to sync up. 
Somewhere we allowed the git submodule upgrade to happen because TravisCI probably didn't fail even though it should.

**Comment by peterbe** [comment]
Actually, the way to replicate the error is by:
```
▶ CLI_BUILD_HTML=true yarn workspace cli start
...you'll see the `UnhandledPromiseRejectionWarning:` stacktrace here...
▶ echo $?
0
```
