### ISSUE TITLE
Render 'link_list' sections

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#157]
In [this PR](https://github.com/mdn/stumptown-renderer/pull/156) the error handler in the `cli` is getting better. It's going to be more loud and explicit about packaged .json files that throws an exception when trying to create a .html file. One of them is:

```
Rendering HTML failed!
      uri=/en-US/docs/Web/HTML
      filePath=/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/stumptown/packaged/html/HTML.json
Error: No idea how to handle a 'link_list' section
    at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:191:13
    at Array.map (<anonymous>)
    at map (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:148:19)
    at processChild (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3090:1)
    at resolve (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:1)
    at ReactDOMServerRenderer.render (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:1)
    at ReactDOMServerRenderer.read (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:1)
    at renderToString (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:1)
    at ./render.js.__webpack_exports__.default (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/render.js:31:34)
    at buildHtmlAndJson (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/index.js:118:24)
```

The other one is:

```
Rendering HTML failed!
      uri=/en-US/docs/Web/HTML/Applying_color
      filePath=/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/stumptown/packaged/html/guides/Applying_color.json
Error: No idea how to handle a 'example' section
    at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:191:13
    at Array.map (<anonymous>)
    at map (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:148:19)
    at processChild (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3090:1)
    at resolve (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:1)
    at ReactDOMServerRenderer.render (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:1)
    at ReactDOMServerRenderer.read (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:1)
    at renderToString (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:1)
    at ./render.js.__webpack_exports__.default (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/render.js:31:34)
    at buildHtmlAndJson (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/index.js:118:24)
```

We basically need to go back to the `<RenderDocumentBody/>` component and write [more `} else if (...) {` code](https://github.com/mdn/stumptown-renderer/blob/5f960790346d1e2c63b0e591aeaa4d6e424b7df1/client/src/document.js#L189-L191). 

Perhaps @wbamberg can help collect the notes and status on these?

**Comment by joedarc** [comment]
@peterbe I'll gladly take a look at the example section, especially because i believe i updated the submodule when that started getting included. I meant to get around to it but was sidetracked with other work/contributions. 😅

**Comment by wbamberg** [comment]
Yes, those are exactly the errors I would expect to see.

For `example`, this is just like `examples` except that there's only one example, not an array of them, and you shouldn't render an H2 "Examples" before rendering the examples.

For `link_list`, this is, well, a list of links (or an array of links, more accurately I suppose. Perhaps we ought to rename them.)

A `link_list` looks like:

```
    {
      "type": "link_list",
      "value": {
        "title": "Learn HTML",
        "content": [
          {
            "title": "Introduction to HTML",
            "short_title": null,                   // or a text short title
            "mdn_url": "/en-US/docs/Learn/HTML/Introduction_to_HTML",
            "short_description": null              // or an HTML short description
          },
          {
            "title": "Multimedia and Embedding",
            "short_title": null,
            "mdn_url": "/en-US/docs/Learn/HTML/Multimedia_and_embedding",
            "short_description": null
          }
        ]
      }
    }
```

So they have a text `title`, and a `content` which is an array of items that represent links to pages. Each of these objects has:

* `title` (mandatory): text of the link
* `short_title` (optional): you can use this as the link text if you want, and if it exists
* `mdn_url` (mandatory): link target
* `short_description` (currently optional, but probably eventually mandatory): you can include this after the link to provide some context.

At the moment these are used in landing pages. For an example of one way a landing page could be rendered see https://github.com/mdn/stumptown-content/wiki/HTML-landing-page-draft. In that example, the "Learn HTML", "Guides", and "Reference" section could each be represented using a link list.

In MDN landing pages often render lists of links across two columns, and/or in a `<dl>` format, with links as the `<dt>` and the short description as the `<dd>` (e.f. https://developer.mozilla.org/en-US/docs/Web/HTML). But this is a rendering choice, independent of the data structure.

**Comment by peterbe** [comment]
Note-to-self, I changed *this* issue to be exclusively about `link_list`. @joedarc is taking care of `example` in https://github.com/mdn/stumptown-renderer/pull/158

**Comment by peterbe** [comment]
How about, to get momentum, we just add another ingredient component called LinkedList whose input is that `value` array. It doesn't have to be awesome but let's start with that `<dl>` approach which we're currently using on MDN.

**Comment by joedarc** [comment]
@peter i did this https://github.com/mdn/stumptown-renderer/pull/159, yesterday. I just threw together something similar to this: https://github.com/mdn/stumptown-content/wiki/HTML-landing-page-draft.

**Comment by peterbe** [comment]
Done with https://github.com/mdn/stumptown-renderer/pull/159
