### ISSUE TITLE
Redirects don't work in local development

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#450]
Visit http://localhost:3000/en-US/docs/Web/HTML/Element/img for example. 
It has a link like this:
```
<p>This element includes the <a href="/en-US/docs/HTML/Global_attributes">global attributes</a>.</p>
```
But if you go to http://localhost:3000/en-US/docs/HTML/Global_attributes it triggers this error in the server:

```
11:16:52 PM server.1      |  (node:44530) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
11:16:52 PM server.1      |      at validateString (internal/validators.js:120:11)
11:16:52 PM server.1      |      at Object.join (path.js:1039:7)
11:16:52 PM server.1      |      at normalizeContentPath (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/server/index.js:88:15)
11:16:52 PM server.1      |      at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/server/index.js:153:28
11:16:52 PM server.1      |      at Layer.handle [as handle_request] (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/layer.js:95:5)
11:16:52 PM server.1      |      at next (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/route.js:137:13)
11:16:52 PM server.1      |      at Route.dispatch (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/route.js:112:3)
11:16:52 PM server.1      |      at Layer.handle [as handle_request] (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/layer.js:95:5)
11:16:52 PM server.1      |      at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:281:22
11:16:52 PM server.1      |      at param (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:354:14)
11:16:52 PM server.1      |  (node:44530) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by peterbe** [comment]
Note, the reason the link isn't working is because it's a redirect:
```
▶ cat content/files/en-us/_redirects.txt | rg '/en-US/docs/HTML/Global_attributes'
/en-US/docs/HTML/Global_attributes	/en-US/docs/Web/HTML/Global_attributes
```

So somewhere in `server` it needs to be able to look up redirects but it's failing.
