### ISSUE TITLE
Struggling with colons in server on-the-fly-build

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#536]
Steps to reproduce; visit `http://localhost:3000/en-us/docs/web/css/::-webkit-scrollbar`

In the `server` you get:

```
11:06:06 AM server.1      |  Successfully on-the-fly built undefined (7ms)
11:06:06 AM server.1      |  TypeError: path argument is required to res.sendFile
11:06:06 AM server.1      |      at ServerResponse.sendFile (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/response.js:411:11)
11:06:06 AM server.1      |      at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/server/index.js:187:15
11:06:06 AM server.1      |      at Layer.handle [as handle_request] (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/layer.js:95:5)
11:06:06 AM server.1      |      at next (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/route.js:137:13)
11:06:06 AM server.1      |      at Route.dispatch (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/route.js:112:3)
11:06:06 AM server.1      |      at Layer.handle [as handle_request] (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/layer.js:95:5)
11:06:06 AM server.1      |      at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:281:22
11:06:06 AM server.1      |      at param (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:354:14)
11:06:06 AM server.1      |      at param (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:365:14)
11:06:06 AM server.1      |      at Function.process_params (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:410:3)
```

NOTE The invalid `Successfully on-the-fly built undefined`  first line.

**Comment by peterbe** [comment]
Strangely, it works the first time. 

```
1:04:54 PM server.1       |  Successfully on-the-fly built /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/client/build/en-us/docs/web/css/_colon__colon_-webkit-scrollbar/index.json (763ms)
1:05:06 PM server.1       |  Successfully on-the-fly built undefined (2ms)
1:05:06 PM server.1       |  TypeError: path argument is required to res.sendFile
1:05:06 PM server.1       |      at ServerResponse.sendFile (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/response.js:411:11)
1:05:06 PM server.1       |      at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/server/index.js:187:15
1:05:06 PM server.1       |      at Layer.handle [as handle_request] (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/layer.js:95:5)
1:05:06 PM server.1       |      at next (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/route.js:137:13)
1:05:06 PM server.1       |      at Route.dispatch (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/route.js:112:3)
1:05:06 PM server.1       |      at Layer.handle [as handle_request] (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/layer.js:95:5)
1:05:06 PM server.1       |      at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:281:22
1:05:06 PM server.1       |      at param (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:354:14)
1:05:06 PM server.1       |      at param (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:365:14)
1:05:06 PM server.1       |      at Function.process_params (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:410:3)
```
