### ISSUE TITLE
Drop Babel from cli

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#74]
If I remember correctly, the only reason we're using Babel to transform `cli/index.js` into `cli/dist/cli.js`, with Babel (and Webpack), is for the sake of module importing. 
If we just switch from `import minimist from "minimist";` to `const minimist = require("minimist");` we might be able to run everything without transpilation in Node 10. 

There might be other features that Babel allows us, but stuff like fat arrow functions etc are perfectly fine in Node >=10 for example.

**Comment by peterbe** [comment]
One annoying thing about having to execute the transpiled JS code is the stack traces are cryptic. E.g. 
```
/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/index.js:127
      ? JSON.stringify(options, null, 2)
             ^
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'root' -> object with constructor 'Node'
    |     property 'children' -> object with constructor 'Array'
    --- index 0 closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/index.js:127:14)
    at buildHtmlAndJson (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/index.js:209:5)
    at FSReqCallback.oncomplete (fs.js:153:23)
```

What the heck is `stumptown-renderer/cli/dist/webpack:/index.js`?

**Comment by peterbe** [comment]
Nevermind. It doesn't make sense. The `cli/index.js` uses `import { App } from "../client/src/app";`
So, if you remove all the stuff that needs Babel, such as module loading, you can make do without webpack and babel and stuff. However, because we're importing the client-side `App` component that too gets roped in. 

The client app needs to be Babelifed because we want to compile the JS code down to a version of JS code is supported in most browsers. Also, the app code is most conveniently written with JSX and with module imports so we wouldn't want to change that. The only JSX that was in the `cli` was the `@reach/router` `ServerLocation` component.
